# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  - trigger: "a\""
    replace: "ä"

  - trigger: "o\""
    replace: "ö"

  - trigger: "u\""
    replace: "ü"

  - trigger: "s\""
    replace: "ß"

  - trigger: "A\""
    replace: "Ä"

  - trigger: "O\""
    replace: "Ö"

  - trigger: "U\""
    replace: "Ü"

  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
